/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 78
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 45
#define ALIAS_COUNT 1
#define TOKEN_COUNT 26
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__directive_single_line_token1 = 1,
  aux_sym__directive_single_line_token2 = 2,
  sym__directive_content = 3,
  anon_sym_BANGpath = 4,
  anon_sym_LBRACE = 5,
  anon_sym_RBRACE = 6,
  aux_sym__directive_multiline_content_token1 = 7,
  sym__python_block = 8,
  anon_sym_LT = 9,
  anon_sym_GT = 10,
  anon_sym_LT_SLASH = 11,
  anon_sym_SLASH_GT = 12,
  aux_sym_tag_name_token1 = 13,
  anon_sym_EQ = 14,
  aux_sym__attribute_name_token1 = 15,
  aux_sym__attribute_name_token2 = 16,
  aux_sym__attribute_name_token3 = 17,
  anon_sym_DQUOTE = 18,
  aux_sym_attribute_value_token1 = 19,
  anon_sym_SQUOTE = 20,
  aux_sym_attribute_value_token2 = 21,
  sym_separator = 22,
  sym_text = 23,
  sym_hyphen = 24,
  sym_comment = 25,
  sym_source_file = 26,
  sym_directive = 27,
  sym__directive_single_line = 28,
  sym__directive_multiline = 29,
  sym__directive_multiline_content = 30,
  sym_python_section = 31,
  sym__html_content = 32,
  sym_tag = 33,
  sym_self_closing_tag = 34,
  sym_tag_name = 35,
  sym_attribute = 36,
  sym__attribute_name = 37,
  sym_attribute_value = 38,
  sym_interpolation = 39,
  sym__interpolation_content = 40,
  aux_sym_source_file_repeat1 = 41,
  aux_sym__directive_multiline_repeat1 = 42,
  aux_sym_tag_repeat1 = 43,
  aux_sym_tag_repeat2 = 44,
  alias_sym_attribute_name = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__directive_single_line_token1] = "keyword_directive",
  [aux_sym__directive_single_line_token2] = "_directive_single_line_token2",
  [sym__directive_content] = "_directive_content",
  [anon_sym_BANGpath] = "keyword_directive",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [aux_sym__directive_multiline_content_token1] = "_directive_multiline_content_token1",
  [sym__python_block] = "python_code",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [aux_sym_tag_name_token1] = "tag_name_token1",
  [anon_sym_EQ] = "=",
  [aux_sym__attribute_name_token1] = "special_attribute_name",
  [aux_sym__attribute_name_token2] = "special_attribute_name",
  [aux_sym__attribute_name_token3] = "special_attribute_name",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_attribute_value_token1] = "attribute_content",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_attribute_value_token2] = "attribute_content",
  [sym_separator] = "separator",
  [sym_text] = "text",
  [sym_hyphen] = "hyphen",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym_directive] = "directive",
  [sym__directive_single_line] = "_directive_single_line",
  [sym__directive_multiline] = "_directive_multiline",
  [sym__directive_multiline_content] = "python_code",
  [sym_python_section] = "python_section",
  [sym__html_content] = "_html_content",
  [sym_tag] = "tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_tag_name] = "tag_name",
  [sym_attribute] = "attribute",
  [sym__attribute_name] = "_attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_interpolation] = "interpolation",
  [sym__interpolation_content] = "python_code",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym__directive_multiline_repeat1] = "_directive_multiline_repeat1",
  [aux_sym_tag_repeat1] = "tag_repeat1",
  [aux_sym_tag_repeat2] = "tag_repeat2",
  [alias_sym_attribute_name] = "attribute_name",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__directive_single_line_token1] = aux_sym__directive_single_line_token1,
  [aux_sym__directive_single_line_token2] = aux_sym__directive_single_line_token2,
  [sym__directive_content] = sym__directive_content,
  [anon_sym_BANGpath] = aux_sym__directive_single_line_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [aux_sym__directive_multiline_content_token1] = aux_sym__directive_multiline_content_token1,
  [sym__python_block] = sym__python_block,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [aux_sym_tag_name_token1] = aux_sym_tag_name_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [aux_sym__attribute_name_token1] = aux_sym__attribute_name_token1,
  [aux_sym__attribute_name_token2] = aux_sym__attribute_name_token1,
  [aux_sym__attribute_name_token3] = aux_sym__attribute_name_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_attribute_value_token1] = aux_sym_attribute_value_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_attribute_value_token2] = aux_sym_attribute_value_token1,
  [sym_separator] = sym_separator,
  [sym_text] = sym_text,
  [sym_hyphen] = sym_hyphen,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym_directive] = sym_directive,
  [sym__directive_single_line] = sym__directive_single_line,
  [sym__directive_multiline] = sym__directive_multiline,
  [sym__directive_multiline_content] = sym__python_block,
  [sym_python_section] = sym_python_section,
  [sym__html_content] = sym__html_content,
  [sym_tag] = sym_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_tag_name] = sym_tag_name,
  [sym_attribute] = sym_attribute,
  [sym__attribute_name] = sym__attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_interpolation] = sym_interpolation,
  [sym__interpolation_content] = sym__python_block,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym__directive_multiline_repeat1] = aux_sym__directive_multiline_repeat1,
  [aux_sym_tag_repeat1] = aux_sym_tag_repeat1,
  [aux_sym_tag_repeat2] = aux_sym_tag_repeat2,
  [alias_sym_attribute_name] = alias_sym_attribute_name,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__directive_single_line_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__directive_single_line_token2] = {
    .visible = false,
    .named = false,
  },
  [sym__directive_content] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_BANGpath] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__directive_multiline_content_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__python_block] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_tag_name_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__attribute_name_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__attribute_name_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__attribute_name_token3] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [sym_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_hyphen] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_directive] = {
    .visible = true,
    .named = true,
  },
  [sym__directive_single_line] = {
    .visible = false,
    .named = true,
  },
  [sym__directive_multiline] = {
    .visible = false,
    .named = true,
  },
  [sym__directive_multiline_content] = {
    .visible = true,
    .named = true,
  },
  [sym_python_section] = {
    .visible = true,
    .named = true,
  },
  [sym__html_content] = {
    .visible = false,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym__attribute_name] = {
    .visible = false,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [sym__interpolation_content] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__directive_multiline_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tag_repeat2] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = alias_sym_attribute_name,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 4,
  [10] = 6,
  [11] = 7,
  [12] = 5,
  [13] = 13,
  [14] = 14,
  [15] = 13,
  [16] = 16,
  [17] = 17,
  [18] = 17,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 26,
  [38] = 38,
  [39] = 25,
  [40] = 24,
  [41] = 21,
  [42] = 20,
  [43] = 23,
  [44] = 26,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 50,
  [55] = 49,
  [56] = 56,
  [57] = 48,
  [58] = 50,
  [59] = 51,
  [60] = 52,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 66,
  [70] = 70,
  [71] = 61,
  [72] = 72,
  [73] = 65,
  [74] = 66,
  [75] = 72,
  [76] = 76,
  [77] = 77,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(20);
      ADVANCE_MAP(
        '!', 13,
        '"', 75,
        '$', 14,
        '\'', 85,
        '-', 102,
        '/', 11,
        ':', 15,
        '<', 66,
        '=', 71,
        '>', 67,
        '@', 16,
        '{', 37,
        '}', 38,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(29);
      if (lookahead == '<') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(2);
      if (lookahead == '<') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(2);
      END_STATE();
    case 3:
      if (lookahead == '!') ADVANCE(96);
      if (lookahead == '-') ADVANCE(101);
      if (lookahead == '<') ADVANCE(66);
      if (lookahead == '{') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(100);
      END_STATE();
    case 4:
      if (lookahead == '!') ADVANCE(8);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(95);
      END_STATE();
    case 6:
      if (lookahead == '-') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == '-') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == '-') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == '-') ADVANCE(7);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '<') ADVANCE(39);
      if (lookahead == '}') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 11:
      if (lookahead == '>') ADVANCE(69);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(103);
      END_STATE();
    case 13:
      if (lookahead == 'p') ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 14:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 16:
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 17:
      if (lookahead != 0 &&
          lookahead != '-') ADVANCE(9);
      END_STATE();
    case 18:
      if (eof) ADVANCE(20);
      if (lookahead == '!') ADVANCE(99);
      if (lookahead == '-') ADVANCE(102);
      if (lookahead == '<') ADVANCE(65);
      if (lookahead == '{') ADVANCE(37);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(100);
      END_STATE();
    case 19:
      if (eof) ADVANCE(20);
      if (lookahead == '!') ADVANCE(60);
      if (lookahead == '-') ADVANCE(53);
      if (lookahead == '<') ADVANCE(49);
      if (lookahead == '{') ADVANCE(64);
      if (lookahead == '}') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token1);
      if (lookahead == 'a') ADVANCE(23);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token1);
      if (lookahead == 'h') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token1);
      if (lookahead == 't') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token2);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(29);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym__directive_single_line_token2);
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '\r') ADVANCE(2);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '-') ADVANCE(35);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '\n') ADVANCE(9);
      if (lookahead == '-') ADVANCE(32);
      if (lookahead != 0) ADVANCE(28);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '\n') ADVANCE(25);
      if (lookahead == '\r') ADVANCE(29);
      if (lookahead == '<') ADVANCE(30);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0) ADVANCE(35);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '!') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(35);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '-') ADVANCE(27);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(35);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(35);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '-') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(35);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead == '>') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(35);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym__directive_content);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(35);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_BANGpath);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '!') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(47);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '-') ADVANCE(47);
      if (lookahead == '}') ADVANCE(9);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '-') ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(47);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '-') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(47);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '-') ADVANCE(42);
      if (lookahead == '}') ADVANCE(9);
      if (lookahead != 0) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '<') ADVANCE(39);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(47);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead == '>') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym__directive_multiline_content_token1);
      if (lookahead != 0 &&
          lookahead != '}') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '!') ADVANCE(60);
      if (lookahead == '-') ADVANCE(53);
      if (lookahead == '<') ADVANCE(49);
      if (lookahead == '{') ADVANCE(64);
      if (lookahead == '}') ADVANCE(64);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(48);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '!') ADVANCE(56);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(64);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(64);
      if (lookahead != 0) ADVANCE(55);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(57);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(50);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(51);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(52);
      if (lookahead != 0) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '-') ADVANCE(54);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '>') ADVANCE(64);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == 'a') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == 'h') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == 'p') ADVANCE(58);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == 't') ADVANCE(59);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead == '!' ||
          lookahead == '-' ||
          lookahead == '<' ||
          lookahead == '{' ||
          lookahead == '}') ADVANCE(64);
      if (lookahead != 0) ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym__python_block);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym__python_block);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(8);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '!') ADVANCE(8);
      if (lookahead == '/') ADVANCE(68);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_tag_name_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(aux_sym__attribute_name_token1);
      if (lookahead == '.' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(aux_sym__attribute_name_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym__attribute_name_token3);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '!') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '"') ADVANCE(84);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '-') ADVANCE(84);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '"') ADVANCE(9);
      if (lookahead == '-') ADVANCE(80);
      if (lookahead != 0) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '-') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(84);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '-') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(84);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '-') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(84);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '<') ADVANCE(76);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(84);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead == '>') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(84);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(aux_sym_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(84);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '!') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(94);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '-') ADVANCE(94);
      if (lookahead != 0) ADVANCE(88);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '\'') ADVANCE(9);
      if (lookahead == '-') ADVANCE(90);
      if (lookahead != 0) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '-') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(94);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '-') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(94);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '-') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(94);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '<') ADVANCE(86);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(94);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead == '>') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(94);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(aux_sym_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(94);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_separator);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_text);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '!') ADVANCE(99);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '<' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(100);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == '!') ADVANCE(96);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != '-' &&
          lookahead != '<' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(100);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'p') ADVANCE(21);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(24);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '!' &&
          lookahead != '-' &&
          lookahead != '<' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(100);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_hyphen);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_hyphen);
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 18},
  [2] = {.lex_state = 18},
  [3] = {.lex_state = 18},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 3},
  [7] = {.lex_state = 3},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 3},
  [10] = {.lex_state = 3},
  [11] = {.lex_state = 3},
  [12] = {.lex_state = 3},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 19},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 18},
  [20] = {.lex_state = 18},
  [21] = {.lex_state = 18},
  [22] = {.lex_state = 18},
  [23] = {.lex_state = 18},
  [24] = {.lex_state = 18},
  [25] = {.lex_state = 18},
  [26] = {.lex_state = 18},
  [27] = {.lex_state = 18},
  [28] = {.lex_state = 18},
  [29] = {.lex_state = 18},
  [30] = {.lex_state = 18},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 3},
  [41] = {.lex_state = 3},
  [42] = {.lex_state = 3},
  [43] = {.lex_state = 3},
  [44] = {.lex_state = 3},
  [45] = {.lex_state = 10},
  [46] = {.lex_state = 10},
  [47] = {.lex_state = 10},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 10},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 10},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 10},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 10},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 0},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 82},
  [68] = {.lex_state = 92},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 2},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym__directive_single_line_token1] = ACTIONS(1),
    [anon_sym_BANGpath] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [aux_sym_tag_name_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [aux_sym__attribute_name_token1] = ACTIONS(1),
    [aux_sym__attribute_name_token2] = ACTIONS(1),
    [aux_sym__attribute_name_token3] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [sym_separator] = ACTIONS(1),
    [sym_hyphen] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(64),
    [sym_directive] = STATE(2),
    [sym__directive_single_line] = STATE(19),
    [sym__directive_multiline] = STATE(19),
    [sym_python_section] = STATE(2),
    [sym__html_content] = STATE(2),
    [sym_tag] = STATE(2),
    [sym_self_closing_tag] = STATE(2),
    [sym_interpolation] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym__directive_single_line_token1] = ACTIONS(7),
    [anon_sym_BANGpath] = ACTIONS(9),
    [anon_sym_LBRACE] = ACTIONS(11),
    [anon_sym_LT] = ACTIONS(13),
    [sym_separator] = ACTIONS(15),
    [sym_text] = ACTIONS(17),
    [sym_hyphen] = ACTIONS(17),
    [sym_comment] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(7), 1,
      aux_sym__directive_single_line_token1,
    ACTIONS(9), 1,
      anon_sym_BANGpath,
    ACTIONS(11), 1,
      anon_sym_LBRACE,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      sym_separator,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 2,
      sym_text,
      sym_hyphen,
    STATE(19), 2,
      sym__directive_single_line,
      sym__directive_multiline,
    STATE(3), 7,
      sym_directive,
      sym_python_section,
      sym__html_content,
      sym_tag,
      sym_self_closing_tag,
      sym_interpolation,
      aux_sym_source_file_repeat1,
  [39] = 10,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    ACTIONS(27), 1,
      aux_sym__directive_single_line_token1,
    ACTIONS(30), 1,
      anon_sym_BANGpath,
    ACTIONS(33), 1,
      anon_sym_LBRACE,
    ACTIONS(36), 1,
      anon_sym_LT,
    ACTIONS(39), 1,
      sym_separator,
    ACTIONS(42), 2,
      sym_text,
      sym_hyphen,
    STATE(19), 2,
      sym__directive_single_line,
      sym__directive_multiline,
    STATE(3), 7,
      sym_directive,
      sym_python_section,
      sym__html_content,
      sym_tag,
      sym_self_closing_tag,
      sym_interpolation,
      aux_sym_source_file_repeat1,
  [78] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(49), 1,
      anon_sym_LT_SLASH,
    ACTIONS(51), 1,
      sym_text,
    ACTIONS(53), 1,
      sym_hyphen,
    STATE(8), 5,
      sym__html_content,
      sym_tag,
      sym_self_closing_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [104] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    ACTIONS(57), 1,
      sym_text,
    ACTIONS(59), 1,
      sym_hyphen,
    STATE(9), 5,
      sym__html_content,
      sym_tag,
      sym_self_closing_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [130] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(61), 1,
      anon_sym_LT_SLASH,
    ACTIONS(63), 1,
      sym_text,
    ACTIONS(65), 1,
      sym_hyphen,
    STATE(7), 5,
      sym__html_content,
      sym_tag,
      sym_self_closing_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [156] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(51), 1,
      sym_text,
    ACTIONS(53), 1,
      sym_hyphen,
    ACTIONS(55), 1,
      anon_sym_LT_SLASH,
    STATE(8), 5,
      sym__html_content,
      sym_tag,
      sym_self_closing_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [182] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(67), 1,
      anon_sym_LBRACE,
    ACTIONS(70), 1,
      anon_sym_LT,
    ACTIONS(73), 1,
      anon_sym_LT_SLASH,
    ACTIONS(75), 1,
      sym_text,
    ACTIONS(78), 1,
      sym_hyphen,
    STATE(8), 5,
      sym__html_content,
      sym_tag,
      sym_self_closing_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [208] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(51), 1,
      sym_text,
    ACTIONS(53), 1,
      sym_hyphen,
    ACTIONS(81), 1,
      anon_sym_LT_SLASH,
    STATE(8), 5,
      sym__html_content,
      sym_tag,
      sym_self_closing_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [234] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(83), 1,
      anon_sym_LT_SLASH,
    ACTIONS(85), 1,
      sym_text,
    ACTIONS(87), 1,
      sym_hyphen,
    STATE(11), 5,
      sym__html_content,
      sym_tag,
      sym_self_closing_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [260] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(51), 1,
      sym_text,
    ACTIONS(53), 1,
      sym_hyphen,
    ACTIONS(89), 1,
      anon_sym_LT_SLASH,
    STATE(8), 5,
      sym__html_content,
      sym_tag,
      sym_self_closing_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [286] = 7,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(45), 1,
      anon_sym_LBRACE,
    ACTIONS(47), 1,
      anon_sym_LT,
    ACTIONS(89), 1,
      anon_sym_LT_SLASH,
    ACTIONS(91), 1,
      sym_text,
    ACTIONS(93), 1,
      sym_hyphen,
    STATE(4), 5,
      sym__html_content,
      sym_tag,
      sym_self_closing_tag,
      sym_interpolation,
      aux_sym_tag_repeat2,
  [312] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(95), 1,
      anon_sym_GT,
    ACTIONS(97), 1,
      anon_sym_SLASH_GT,
    ACTIONS(99), 1,
      aux_sym_tag_name_token1,
    STATE(32), 1,
      sym__attribute_name,
    STATE(16), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
    ACTIONS(101), 3,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [337] = 4,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(103), 1,
      ts_builtin_sym_end,
    ACTIONS(107), 1,
      sym__python_block,
    ACTIONS(105), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [356] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      aux_sym_tag_name_token1,
    ACTIONS(109), 1,
      anon_sym_GT,
    ACTIONS(111), 1,
      anon_sym_SLASH_GT,
    STATE(32), 1,
      sym__attribute_name,
    STATE(16), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
    ACTIONS(101), 3,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [381] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(115), 1,
      aux_sym_tag_name_token1,
    STATE(32), 1,
      sym__attribute_name,
    ACTIONS(113), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(16), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
    ACTIONS(118), 3,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [404] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      aux_sym_tag_name_token1,
    ACTIONS(121), 1,
      anon_sym_GT,
    ACTIONS(123), 1,
      anon_sym_SLASH_GT,
    STATE(32), 1,
      sym__attribute_name,
    STATE(15), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
    ACTIONS(101), 3,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [429] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(99), 1,
      aux_sym_tag_name_token1,
    ACTIONS(125), 1,
      anon_sym_GT,
    ACTIONS(127), 1,
      anon_sym_SLASH_GT,
    STATE(32), 1,
      sym__attribute_name,
    STATE(13), 2,
      sym_attribute,
      aux_sym_tag_repeat1,
    ACTIONS(101), 3,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [454] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    ACTIONS(131), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [470] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(133), 1,
      ts_builtin_sym_end,
    ACTIONS(135), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [486] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(137), 1,
      ts_builtin_sym_end,
    ACTIONS(139), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [502] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(141), 1,
      ts_builtin_sym_end,
    ACTIONS(143), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [518] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(145), 1,
      ts_builtin_sym_end,
    ACTIONS(147), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [534] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
    ACTIONS(151), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [550] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(153), 1,
      ts_builtin_sym_end,
    ACTIONS(155), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [566] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(157), 1,
      ts_builtin_sym_end,
    ACTIONS(159), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [582] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(161), 1,
      ts_builtin_sym_end,
    ACTIONS(163), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [598] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(165), 1,
      ts_builtin_sym_end,
    ACTIONS(167), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [614] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(169), 1,
      ts_builtin_sym_end,
    ACTIONS(171), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [630] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(173), 1,
      ts_builtin_sym_end,
    ACTIONS(175), 7,
      aux_sym__directive_single_line_token1,
      anon_sym_BANGpath,
      anon_sym_LBRACE,
      anon_sym_LT,
      sym_separator,
      sym_text,
      sym_hyphen,
  [646] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(177), 7,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_tag_name_token1,
      anon_sym_EQ,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [659] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(181), 1,
      anon_sym_EQ,
    ACTIONS(179), 6,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_tag_name_token1,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [674] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(183), 6,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_tag_name_token1,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [686] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(185), 6,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_tag_name_token1,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [698] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(187), 6,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_tag_name_token1,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [710] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(189), 6,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_tag_name_token1,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [722] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(157), 6,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      aux_sym_tag_name_token1,
      aux_sym__attribute_name_token1,
      aux_sym__attribute_name_token2,
      aux_sym__attribute_name_token3,
  [734] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(191), 1,
      anon_sym_LBRACE,
    ACTIONS(193), 1,
      anon_sym_DQUOTE,
    ACTIONS(195), 1,
      anon_sym_SQUOTE,
    STATE(34), 1,
      sym_attribute_value,
    STATE(36), 1,
      sym_interpolation,
  [753] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(153), 1,
      sym_text,
    ACTIONS(155), 4,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_hyphen,
  [766] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(149), 1,
      sym_text,
    ACTIONS(151), 4,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_hyphen,
  [779] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(137), 1,
      sym_text,
    ACTIONS(139), 4,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_hyphen,
  [792] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(133), 1,
      sym_text,
    ACTIONS(135), 4,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_hyphen,
  [805] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(145), 1,
      sym_text,
    ACTIONS(147), 4,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_hyphen,
  [818] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(157), 1,
      sym_text,
    ACTIONS(159), 4,
      anon_sym_LBRACE,
      anon_sym_LT,
      anon_sym_LT_SLASH,
      sym_hyphen,
  [831] = 4,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(197), 1,
      anon_sym_RBRACE,
    ACTIONS(199), 1,
      aux_sym__directive_multiline_content_token1,
    STATE(47), 2,
      sym__directive_multiline_content,
      aux_sym__directive_multiline_repeat1,
  [845] = 4,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(201), 1,
      anon_sym_RBRACE,
    ACTIONS(203), 1,
      aux_sym__directive_multiline_content_token1,
    STATE(46), 2,
      sym__directive_multiline_content,
      aux_sym__directive_multiline_repeat1,
  [859] = 4,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(199), 1,
      aux_sym__directive_multiline_content_token1,
    ACTIONS(206), 1,
      anon_sym_RBRACE,
    STATE(46), 2,
      sym__directive_multiline_content,
      aux_sym__directive_multiline_repeat1,
  [873] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      aux_sym_tag_name_token1,
    STATE(73), 1,
      sym_tag_name,
  [883] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      aux_sym_tag_name_token1,
    STATE(61), 1,
      sym_tag_name,
  [893] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(210), 1,
      aux_sym__directive_multiline_content_token1,
    STATE(66), 1,
      sym__interpolation_content,
  [903] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      aux_sym_tag_name_token1,
    STATE(17), 1,
      sym_tag_name,
  [913] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      aux_sym_tag_name_token1,
    STATE(75), 1,
      sym_tag_name,
  [923] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(212), 1,
      aux_sym__directive_single_line_token2,
    ACTIONS(214), 1,
      sym__directive_content,
  [933] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(210), 1,
      aux_sym__directive_multiline_content_token1,
    STATE(74), 1,
      sym__interpolation_content,
  [943] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      aux_sym_tag_name_token1,
    STATE(71), 1,
      sym_tag_name,
  [953] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(216), 2,
      anon_sym_RBRACE,
      aux_sym__directive_multiline_content_token1,
  [961] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      aux_sym_tag_name_token1,
    STATE(65), 1,
      sym_tag_name,
  [971] = 3,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(210), 1,
      aux_sym__directive_multiline_content_token1,
    STATE(69), 1,
      sym__interpolation_content,
  [981] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      aux_sym_tag_name_token1,
    STATE(18), 1,
      sym_tag_name,
  [991] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      aux_sym_tag_name_token1,
    STATE(72), 1,
      sym_tag_name,
  [1001] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(218), 1,
      anon_sym_GT,
  [1008] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(220), 1,
      anon_sym_LBRACE,
  [1015] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(222), 1,
      anon_sym_RBRACE,
  [1022] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(224), 1,
      ts_builtin_sym_end,
  [1029] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(226), 1,
      anon_sym_GT,
  [1036] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(228), 1,
      anon_sym_RBRACE,
  [1043] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(230), 1,
      aux_sym_attribute_value_token1,
  [1050] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(232), 1,
      aux_sym_attribute_value_token2,
  [1057] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 1,
      anon_sym_RBRACE,
  [1064] = 2,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(236), 1,
      aux_sym__directive_single_line_token2,
  [1071] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(238), 1,
      anon_sym_GT,
  [1078] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_GT,
  [1085] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(242), 1,
      anon_sym_GT,
  [1092] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_RBRACE,
  [1099] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(246), 1,
      anon_sym_GT,
  [1106] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_DQUOTE,
  [1113] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_SQUOTE,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 39,
  [SMALL_STATE(4)] = 78,
  [SMALL_STATE(5)] = 104,
  [SMALL_STATE(6)] = 130,
  [SMALL_STATE(7)] = 156,
  [SMALL_STATE(8)] = 182,
  [SMALL_STATE(9)] = 208,
  [SMALL_STATE(10)] = 234,
  [SMALL_STATE(11)] = 260,
  [SMALL_STATE(12)] = 286,
  [SMALL_STATE(13)] = 312,
  [SMALL_STATE(14)] = 337,
  [SMALL_STATE(15)] = 356,
  [SMALL_STATE(16)] = 381,
  [SMALL_STATE(17)] = 404,
  [SMALL_STATE(18)] = 429,
  [SMALL_STATE(19)] = 454,
  [SMALL_STATE(20)] = 470,
  [SMALL_STATE(21)] = 486,
  [SMALL_STATE(22)] = 502,
  [SMALL_STATE(23)] = 518,
  [SMALL_STATE(24)] = 534,
  [SMALL_STATE(25)] = 550,
  [SMALL_STATE(26)] = 566,
  [SMALL_STATE(27)] = 582,
  [SMALL_STATE(28)] = 598,
  [SMALL_STATE(29)] = 614,
  [SMALL_STATE(30)] = 630,
  [SMALL_STATE(31)] = 646,
  [SMALL_STATE(32)] = 659,
  [SMALL_STATE(33)] = 674,
  [SMALL_STATE(34)] = 686,
  [SMALL_STATE(35)] = 698,
  [SMALL_STATE(36)] = 710,
  [SMALL_STATE(37)] = 722,
  [SMALL_STATE(38)] = 734,
  [SMALL_STATE(39)] = 753,
  [SMALL_STATE(40)] = 766,
  [SMALL_STATE(41)] = 779,
  [SMALL_STATE(42)] = 792,
  [SMALL_STATE(43)] = 805,
  [SMALL_STATE(44)] = 818,
  [SMALL_STATE(45)] = 831,
  [SMALL_STATE(46)] = 845,
  [SMALL_STATE(47)] = 859,
  [SMALL_STATE(48)] = 873,
  [SMALL_STATE(49)] = 883,
  [SMALL_STATE(50)] = 893,
  [SMALL_STATE(51)] = 903,
  [SMALL_STATE(52)] = 913,
  [SMALL_STATE(53)] = 923,
  [SMALL_STATE(54)] = 933,
  [SMALL_STATE(55)] = 943,
  [SMALL_STATE(56)] = 953,
  [SMALL_STATE(57)] = 961,
  [SMALL_STATE(58)] = 971,
  [SMALL_STATE(59)] = 981,
  [SMALL_STATE(60)] = 991,
  [SMALL_STATE(61)] = 1001,
  [SMALL_STATE(62)] = 1008,
  [SMALL_STATE(63)] = 1015,
  [SMALL_STATE(64)] = 1022,
  [SMALL_STATE(65)] = 1029,
  [SMALL_STATE(66)] = 1036,
  [SMALL_STATE(67)] = 1043,
  [SMALL_STATE(68)] = 1050,
  [SMALL_STATE(69)] = 1057,
  [SMALL_STATE(70)] = 1064,
  [SMALL_STATE(71)] = 1071,
  [SMALL_STATE(72)] = 1078,
  [SMALL_STATE(73)] = 1085,
  [SMALL_STATE(74)] = 1092,
  [SMALL_STATE(75)] = 1099,
  [SMALL_STATE(76)] = 1106,
  [SMALL_STATE(77)] = 1113,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(62),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [27] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(53),
  [30] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [45] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [59] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat2, 2, 0, 0), SHIFT_REPEAT(58),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat2, 2, 0, 0), SHIFT_REPEAT(59),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_tag_repeat2, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_repeat2, 2, 0, 0), SHIFT_REPEAT(8),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_tag_repeat2, 2, 0, 0), SHIFT_REPEAT(8),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_section, 1, 0, 0),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_python_section, 1, 0, 0),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0),
  [115] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_directive, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_directive, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 6, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 6, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_python_section, 2, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_python_section, 2, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 7, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 7, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 8, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag, 8, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive_multiline, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__directive_multiline, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive_single_line, 3, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__directive_single_line, 3, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive_multiline, 4, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__directive_multiline, 4, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__directive_single_line, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__directive_single_line, 2, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__attribute_name, 1, 0, 1),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_name, 1, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute_value, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [193] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [197] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [199] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__directive_multiline_repeat1, 2, 0, 0),
  [203] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__directive_multiline_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [206] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [210] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [212] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [214] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__directive_multiline_content, 1, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__interpolation_content, 1, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [230] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [232] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_pywire(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
